### PR TITLE
Add more state and standards activity

### LINKED ISSUE #4: more things to isolate
Here's a list of additional things that are isolated by `privacy.firstparty.isolate` in Firefox and Tor Browser:

* speculative connections
* fetch caching and requests
* XHR caching and requests
* HPKP
* OCSP cache and requests
* intermediate CA cache
* auto form-fill
* favicon cache
* page info media previews
* image cache
* "save page as" requests

### PR DESCRIPTION
**Pull request by annevk**
Closes #4.

@arthuredelstein I cannot ask for your review directly, but I'd appreciate it!

### CODE REVIEW

**Comment by annevk** [comment]
I ended up excluding "page info media previews", but maybe that's the wrong call? I should probably redo non-standardized state a bit as an enumeration of things implementations ought to consider in addition to what standards require to be robust. Makes sense?

**Comment by arthuredelstein** [comment]
Hi Anne, yes - I think a "non-standard" or "in-browser" checklist that gives examples can be very useful. Leaks via Page Info, Save Page As, Favicons and auto form-fill were all things that happened in Firefox before they were isolated.

Additionally, I would suggest including subcategories. For example, as I recall in Firefox the image cache needed to be isolated in addition to the HTTP cache. And, as there are many kinds of connections (speculative, prefetch, OCSP) it's useful to list these somewhere to help missing them.

**Comment by annevk** [comment]
Thanks, I think I have them all listed now.

**Comment by arthuredelstein** [comment]
Looks great. Thanks!

**Pull request merged**
