### PR TITLE
Add shader caches to the list.

### PR DESCRIPTION
**Pull request by Kangz**
FYI @kainino0x @kvark @kenrussell @domenic

### CODE REVIEW

**Comment by annevk** [comment]
Are there open issues against WebGL and WebGPU to formalize this? It would be good to be able to link them from here.

**Comment by Kangz** [comment]
These caches are non-observable by applications except with timing differences in compilation so I don't know if they can be specced normatively. I don't think WebGL have anything but I opened a [PR](https://github.com/gpuweb/gpuweb/pull/1656) on WebGPU to a non-normative section about "User Agent State" with a link to this repo.

**Comment by annevk** [comment]
Can you file an issue against WebGL for it to add equivalent text to its security/privacy considerations? And then maybe we should add a parenthetical here along the lines of:

> (standardized in WebGL/WebGPU by highlighting the risk in the security/privacy consideration section as the caches are only observable through timing)

**Comment by Kangz** [comment]
Thanks @kenrussell for opening the issue on WebGL https://github.com/KhronosGroup/WebGL/issues/3280

**Comment by Kangz** [comment]
Done!

**Pull request merged**
